### ISSUE TITLE
Schema validator

### ISSUE THREAD

**Issue by samuelmolinari** [foodoclock/foodoclock.github.io#5] opened 2015-01-31 08:48 UTC

**Comment by timstott** [comment] 2015-02-01 11:21
It's not very apparent yet how the schema validator is going to be used. I'm not sure [this interface](https://github.com/foodoclock/recipe-schema/blob/11abb94d0faadc219e4589a15c61217d38962bc1/validator.js#L7) is best. We'll find out soon enough

**Comment by timstott** [comment] 2015-03-21 21:18
Isn't this issue a duplicate of #11? In which case we can close this.

**Closed** 2015-04-19 15:19 UTC
Labels: CI
